<div class="row g-3 mb-4">
    @include('analytics.partials.metric', ['label' => 'Resolution Rate', 'value' => $periodResolutionRate === null ? '—' : number_format($periodResolutionRate, 1).'%', 'description' => 'Resolved now ÷ cases filed in '.$periodLabel, 'icon' => 'bi-bullseye', 'tone' => 'metric-dark'])
    @include('analytics.partials.metric', ['label' => 'Resolved This Period', 'value' => number_format($resolvedThisPeriod), 'description' => 'Recorded resolution date in period', 'icon' => 'bi-file-earmark-check', 'tone' => 'metric-blue'])
    @include('analytics.partials.metric', ['label' => 'Closed This Period', 'value' => number_format($closedThisPeriod), 'description' => 'Other closures, including referrals and dismissals', 'icon' => 'bi-folder2'])
    @include('analytics.partials.metric', ['label' => 'Avg. Resolution Time', 'value' => $periodAverageResolution === null ? '—' : number_format($periodAverageResolution, 1).' days', 'description' => $resolutionDurations->count().' resolved cases with usable dates', 'icon' => 'bi-clock'])
    @include('analytics.partials.metric', ['label' => 'Open-to-Resolved Conversion', 'value' => $conversionRate === null ? '—' : number_format($conversionRate, 1).'%', 'description' => $convertedCases.' of '.$conversionSamples.' tracked openings in period', 'icon' => 'bi-graph-up-arrow'])
    @include('analytics.partials.metric', ['label' => 'Unresolved Cases', 'value' => number_format($openCases), 'description' => 'Matching cases currently open', 'icon' => 'bi-folder2-open'])
</div>
<div class="row g-3 mb-4">
    <div class="col-xl-4">@include('analytics.partials.dashboard-chart', ['id' => 'performanceResolved', 'title' => 'Resolution Trend by Month', 'description' => 'Recorded resolution dates in '.$periodLabel.'.', 'rows' => $resolutionTrend])</div>
    <div class="col-xl-4">@include('analytics.partials.dashboard-chart', ['id' => 'performanceOpenedResolved', 'title' => 'Cases Filed vs Resolved Over Time', 'description' => 'Monthly filing and resolution events; these may refer to different cases.', 'rows' => $openResolvedRows, 'series' => ['Opened / Filed' => 'Filed', 'Resolved' => 'Resolved'], 'chartType' => 'line'])</div>
    <div class="col-xl-4">@include('analytics.partials.dashboard-chart', ['id' => 'performanceTypeTime', 'title' => 'Average Resolution Time by Incident Type', 'description' => 'Average days from report to resolution, using only resolved cases with valid dates. Unresolved cases have no completed resolution time and are excluded.', 'rows' => $resolutionTimeByType, 'horizontal' => true, 'unit' => 'days', 'valueLabel' => 'Average days'])</div>
    <div class="col-xl-4">@include('analytics.partials.dashboard-chart', ['id' => 'performanceOutcomes', 'title' => 'Case Outcome Distribution', 'description' => 'Mutually exclusive completed outcomes by resolution/closure date in '.$periodLabel.'.', 'rows' => $periodOutcomes, 'chartType' => 'doughnut'])</div>
    <div class="col-xl-8">@include('analytics.partials.dashboard-chart', ['id' => 'performanceOutcomeMix', 'title' => 'Monthly Outcome Mix', 'description' => 'Resolved, other closed, referred, and dismissed cases by recorded completion month.', 'rows' => $monthlyOutcomeRows, 'series' => ['Settled / Resolved' => 'Settled / Resolved', 'Other Closed' => 'Other Closed', 'CFA / Referred' => 'CFA / Referred', 'Dismissed' => 'Dismissed'], 'stacked' => true])</div>
</div>
<div class="row g-3 mb-4">
    <div class="col-xl-8"><div class="card h-100"><div class="card-header"><strong>Performance Summary</strong></div>
        <div class="card-body small text-muted">Filings use report dates; resolution and closure counts use completion dates. The rate measures how many cases filed in that month are currently resolved.</div>
        <div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th scope="col">Month</th><th scope="col">Cases Filed</th><th scope="col">Cases Resolved</th><th scope="col">Cases Closed</th><th scope="col">Filing Cohort Resolution Rate</th><th scope="col">Avg. Resolution Days</th></tr></thead><tbody>
            @forelse($performanceSummary as $row)<tr><td>{{ $row['label'] }}</td><td>{{ number_format($row['filed']) }}</td><td>{{ number_format($row['resolved']) }}</td><td>{{ number_format($row['closed'] + $row['referred'] + $row['dismissed']) }}</td><td>{{ $row['resolution_rate'] === null ? '—' : number_format($row['resolution_rate'], 1).'%' }}</td><td>{{ $row['avg_days'] === null ? '—' : number_format($row['avg_days'], 1) }}</td></tr>
            @empty<tr><td colspan="6" class="text-center text-muted py-4">No filing or completion dates available.</td></tr>@endforelse
        </tbody></table></div>
    </div></div>
    <div class="col-xl-4"><div class="card h-100"><div class="card-header"><strong>Outcome Highlights</strong></div><div class="card-body">
        <div class="analytics-highlight"><i class="bi bi-graph-up text-success" aria-hidden="true"></i><div><strong>{{ $periodResolutionRate === null ? 'Unavailable' : number_format($periodResolutionRate, 1).'% Resolution Rate' }}</strong><div class="small text-muted">{{ number_format($filedThisPeriod) }} cases filed during {{ $periodLabel }}.</div></div></div>
        <div class="analytics-highlight"><i class="bi bi-clock text-primary" aria-hidden="true"></i><div><strong>{{ $periodAverageResolution === null ? 'Unavailable' : number_format($periodAverageResolution, 1).' days Average Resolution Time' }}</strong><div class="small text-muted">{{ $resolutionDurations->count() }} recorded resolution durations.</div></div></div>
        <div class="analytics-highlight"><i class="bi bi-bar-chart text-primary" aria-hidden="true"></i><div><strong>{{ $conversionRate === null ? 'Unavailable' : number_format($conversionRate, 1).'% Open-to-Resolved Conversion' }}</strong><div class="small text-muted">Only cases with a recorded opening event are included. Older untracked openings are excluded.</div></div></div>
        <div class="analytics-highlight"><i class="bi bi-file-earmark-check text-primary" aria-hidden="true"></i><div><strong>{{ number_format($closedThisPeriod) }} Cases Closed</strong><div class="small text-muted">Other closures remain separate from resolution.</div></div></div>
    </div></div></div>
</div>
<details class="card mb-4"><summary class="card-header"><strong>Resolution Measurement & Coverage</strong></summary><div class="card-body">
    <p class="mb-2">Across all matching incident records, {{ number_format($resolvedCases) }} are Resolved out of {{ number_format($totalCases) }}: {{ $resolutionRate === null ? 'Unavailable' : number_format($resolutionRate, 1).'%' }}. Dismissals and referrals do not increase this rate.</p>
    <p class="mb-0 text-muted">Average time runs from the report date to the recorded case resolution date. Across all matching records, {{ number_format($resolutionSamples) }} usable dates are included; {{ number_format($missingResolutionDates) }} resolved records have missing or invalid dates and are excluded. Period charts additionally require completion dates in the selected reporting year.</p>
</div></details>
